# TensorFlow Basics

TensorFlow uses **Keras** API as an interface for developing Machine Learning Applications. Keras covers every step of the machine learning workflow, from data processing to hyperparameter tuning to deployment. It was developed with a focus on enabling fast experimentation.


### Keras Core Components

**Layers**: simple input/output transformation. Encapsulates a state (weights) and a computaion method.

**Models**: A directed graph of layers. It's an object that groups layers and that can be trained on data. 

`Sequential`: the simplest model. Linear stack of layers.

`Model` Class: `tf.keras.Model`:has built-in methods for training and testing.

- `tf.keras.Model.fit`: trains the model (with a fixed number of epochs)
- `tf.keras.Model.predict`: inference from samples
- `tf.keras.Model.evaluate`: returns loss and metrics
- `tf.keras.Model.compile`: sets the loss and evaluation method.


### Creating a simple Sequential model

It is appropiate for a _plain stick of layers_ where each layer has **exactly** one input tensor and one output tensor


In [1]:
import numpy as np
import tensorflow as tf
# from tensorflow import keras
# from keras import layers

# Define Sequential model with 3 layers 
# Dense is a Fully Connected Layer with N neurons and activation function.
# model = keras.Sequential(
#     [
#         layers.Dense(2, activation="relu", name="layer1"),
#         layers.Dense(3, activation="relu", name="layer2"),
#         layers.Dense(4, name="layer3")
#     ]
# )

# # call model on a test input
# x = tf.ones((3,3))
# y = model(x)



In [5]:
from keras import layers

# Define Sequential model with 3 layers 
# Dense is a Fully Connected Layer with N neurons and activation function.
model = tf.keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3")
    ]
)

# call model on a test input
x = tf.ones((3,3))
y = model(x)

print(y)

tf.Tensor(
[[-0.06004147  0.16744421  0.122429   -0.03715298]
 [-0.06004147  0.16744421  0.122429   -0.03715298]
 [-0.06004147  0.16744421  0.122429   -0.03715298]], shape=(3, 4), dtype=float32)
